[sprites]

[sprites.cirno]
texture = "cirno.png"
size = [20, 40]
hitbox = "points"
hitbox_bounds = [[10, 20], [10, 20], [10, -20], [-10, -20]]
max_amount = 100

[sprites.red_bullet]
texture = "bullet.png"
size = [5, 5]
hitbox = "sphere"
radius = 5
max_amount = 10000

[enemies]

[enemies.basic_curve]
sprite = "cirno"
health = 10
damage = 5

[enemies.circle]
sprite = "cirno"
health = 5
damage = 5

[bullets]

[bullets.basic_straight]
sprite = "red_bullet"
radius = 5
damage = 10
behavior = "straight"

[level]

[level.pstart]
time = { after = "start", delay = 0.0 }
spawn = { type = "player", position = [0, -180] }

[level.wave0]
time = {after = "start", delay = 1.0}

[level.wave0.spawn]
type = "enemy"
enemy_id = "basic_curve"
pattern = { type = "point", position = [-200, 150], amount = 5, time_int = 0.2 }
repeat = 2
repeat_delay = 4.0
mirror_x = true

[[level.wave0.spawn.paths]]
type = "curve"
points = [["current"], [200, 150]]
speed = 100

[level.wave0.spawn.paths.action]
type = "bullets"
time_start = 1.0
bullet_id = "basic_straight"
pattern = { type = "arc", amount = 20, astart = 0.0, aend = -360.0, speed = 100, time_int = 0.0, radius = 10.0, repeat = 10, repeat_delay = 0.05 }

[level.wave1]
time = {after = "start", delay = 5.0}

[level.wave1.spawn]
type = "enemy"
enemy_id = "basic_curve"
pattern = { type = "point", position = [-200, 180], amount = 5, time_int = 0.5 }
repeat = 2
repeat_delay = 4.0
mirror_x = true

[[level.wave1.spawn.paths]]
type = "curve"
points = [[-200, 180], [-50, 140], [-200, 50]]
speed = 40

[level.wave1.spawn.paths.action]
type = "bullets"
time_start = 1.0
bullet_id = "basic_straight" 
pattern = { type = "point", angle = "player", speed = 80, amount = 5, time_int = 0.5 }

[level.wave2]
time = { after = "start", delay = 8.0 }

# Somewhat more complex wave, spawns 10 enemies in a circle, has them move clockwise in a half circle, then curve out, and shoot 25 bullet 60 degree arcs
[level.wave2.spawn]
type = "enemy"
enemy_id = "circle"
pattern = { type = "arc", center = [-50, 50], radius = 25, astart = 0, aend = 360, amount = 10, time_int = 0.5 }
repeat = 1
repeat_delay = 2.0
mirror_x = true

[[level.wave2.spawn.paths]]
type = "arc"
center = [-50, 50]
radius = 25
start = "current"
degrees = 180
direction = "clockwise"
speed = 40
action = { type = "none" }

[[level.wave2.spawn.paths]]
type = "curve"
points = [["current"], [75, 0], [200, 0]]
speed = 60

[level.wave2.spawn.paths.action]
type = "bullets"
time_start = 1.0
bullet_id = "basic_straight"
pattern = { type = "arc", amount = 5, astart = 240.0, aend = 300.0, speed = 80, time_int = 0.3, radius = 10.0 }
